<div align="center"><span style="font-family: Arial; color:#0000FF"><b>
    <span style="font-size: x-large">Métodos Numéricos II</span>
    <br>
    <span style="font-size: large">Segundo de Grado en Matemáticas - Curso 2022/23</span>
    <br>
    <span style="font-size: medium">Facultad de Ciencias de la Universidad de Málaga</span>
    <br>
    <span style="font-size: small">Dpto. de Análisis Matemático, Estadística e Investigación Operativa, y Matemática Aplicada</span>
    <br>
    <span style="font-size: small">Profs. Manuel J. Castro y Francisco J. Palma (Área Conocimiento de Matemática Aplicada)</span>
    <br>
    <span style="font-size: medium; color:#FF0000">Práctica número 5</span>
    </b></span></div>

In [1]:
from algoritmos import *

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    El objetivo de esta práctica es definir funciones <span style="font-family: Courier">Python</span> para resolver sistemas de ecuaciones lineales por <b>métodos directos de tipo Gauss</b>.
    <br>
    Suponemos por tanto dadas $A\in\mathcal{M}_n(\mathbb{K})$ inversible y $B\in\mathbb{K}^n$, y desarrollamos métodos numéricos para calcular $X\in\mathbb{K}^n$ tal que $A\,X = B$.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    El <b>método de Gauss</b> es un <b>método directo</b> de resolución del problema anterior que, formalmente, equivale a calcular una matriz $M\in\mathcal{M}_n(\mathbb{K})$ inversible tal que la matriz $M\,A$ sea <b>triangular superior</b> y, posteriormente, resolver el sistema $(M\,A)\,X = (M\,B)$ mediante un <b>método de remonte</b>.
    <br>
    En la práctica no se calcula dicha matriz $M$, sino que se va <i>triangularizando</i> la matriz $A$ mediante un <b>proceso iterativo</b> de $n-1$ etapas, en cada una de las cuales, tras colocar en la posición diagonal correspondiente un elemento no nulo (<b>pivote</b> de la iteración), se van haciendo nulos a través de adecuadas combinaciones lineales todos los elementos de la columna situados por debajo de la diagonal principal.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    De manera similar, el <b>método de Gauss-Jordan</b> es un <b>método directo</b> de resolución del mismo problema que, formalmente, equivale a calcular una matriz $M\in\mathcal{M}_n(\mathbb{K})$ inversible tal que la matriz $M\,A$ sea <b>diagonal</b> y, posteriormente, resolver el sistema $(M\,A)\,X = (M\,B)$ que es inmediato debido al carácter diagonal de la matriz.
    <br>
    Tampoco aquí en la práctica se calcula dicha matriz $M$, sino que se va <i>diagonalizando</i> la matriz $A$ mediante un <b>proceso iterativo</b> de $n$ etapas, en cada una de las cuales, tras colocar en la posición diagonal correspondiente un elemento no nulo (<b>pivote</b> de la iteración), se van haciendo nulos a través de adecuadas combinaciones lineales todos los elementos de la columna excepto, evidentemente, el situado en la diagonal principal.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    En ambos métodos tiene particular importancia la elección del elemento que en cada iteración ocupa la posición de pivote; las dos técnicas más habituales son la de <b>pivote parcial</b> y la de <b>primer pivote no nulo</b>.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Nos planteamos entonces como primer objetivo elaborar cuatro funciones <span style="font-family: Courier">Python</span>, a las que daremos los nombres de <span style="font-family: Courier">gauss_pp()</span> y <span style="font-family: Courier">gauss_1p()</span>, para el <b>método de Gauss</b>, y <span style="font-family: Courier">gaussjordan_pp()</span> y <span style="font-family: Courier">gaussjordan_1p()</span>, para el de <b>Gauss-Jordan</b>, que implementan ambos algoritmos con las dos <b>técnicas de elección de pivote</b> indicadas anteriormente.
    <br>
    En todos los casos habrá dos <b>argumentos de entrada</b>, que son la matriz $A$ y el segundo miembro $B$, y como <b>salida</b> se obtienen también dos variables, siendo la primera de tipo booleano, en la que los valores <span style="font-family: Courier">True</span> o <span style="font-family: Courier">False</span> indica que se ha resuelto con éxito o no el sistema, y conteniendo la segunda variable la solución o un mensaje de error, respectivamente.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    En todas las funciones que desarrollemos se intentará utilizar la misma terminología y nombre de las variables que se ha visto en clases teóricas y de problemas; de esta manera es posible seguir mejor la programación del algoritmo correspondiente. En cualquier caso, resaltamos los siguientes hechos:
    <ul>
    <li>siempre se trabaja con la idea de que las funciones puedan resolver múltiples sistemas lineales, todos con la misma matriz $A$, de manera simultánea, por lo que supondremos que $B$, y en consecuencia $X$ también, no es un vector de $\mathbb{K}^n$, sino un matriz de $\mathcal{M}_{n\times q}(\mathbb{K})$;</li>
    <li> el bucle principal del proceso iterativo se realiza en la variable <span style="font-family: Courierç">k</span>; recordamos que hay $n-1$ iteraciones en el método de Gauss y $n$ en el de Gauss-Jordan;</li>
    <li> siempre que se haga referencia a las filas de las matrices se utiliza preferentemente el índice <span style="font-family: Courier">i</span>, mientras que para las columnas se utiliza el índice <span style="font-family: Courier">j</span>;</li>
    <li>la fila en la que se localiza la posición del pivote de cada iteración (dependiendo de la estrategia utilizada), se identifica con el índice <span style="font-family: Courier">ik</span>;</li>
    <li>son fácilmente identificables las instrucciones que permutan las filas de la matriz y del segundo miembro, en el caso de que el pivote de la iteración no se encuentre en la posición natural;</li>
    <li>el proceso de hacer ceros por debajo de la diagonal (y por encima también en el caso de Gauss-Jordan), se realiza únicamente si el pivote elegido es mayor o igual en módulo que $10^{-200}$, que es el umbral de precisión elegido;</li>
    <li>en cada iteración solamente se calculan los elementos de la matriz y del segundo miembro que cambian, no realizandose ningún cálculo supérfluo;</li>
    <li>en las posiciones que deberían anularse en la iteración $k$-ésima, es decir, $a_{i,k}^{k+1}$, para $i=k+1,\ldots,n$, (en el caso de Gauss-Jordan también para $i=1,\ldots,k-1$) no se guardan ceros, sino que se almacenan los cocientes $\displaystyle\frac{\alpha_{i,k}^k}{\alpha_{k,k}^k}$, que son los elementos no nulos y no diagonales de la matrix de combinaciones lineales $E_k$ con signo cambiado;</li>
    <li>en el método de Gauss, el proceso de resolución del (de los) sistema(s) se realiza mediante una llamada al programa <span style="font-family: Courier">remonte()</span>, que sería el que detectaría, si fuera el caso, la existencia de elementos nulos (o casi nulos) en la diagonal principal, es decir, detectaría si la matriz es o no regular;</li>
    <li>en el método de Gauss-Jordan, la resolución del (de los) sistema(s), es decir las $n$ divisiones de los elementos del (de los) segundo(s) miembro(s) por los elementos diagonales de $M\,A$, se realiza en el propio código, previa comprobación de que dichos elementos diagonales superen el umbral de precisión elegido.</li>
    </ul>
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 1.</b></span> Elaborar un programa de nombre <span style="font-family: Courier">gauss_pp()</span> que implemente el algoritmo del <b>método de Gauss</b>, con estrategia de <b>pivote parcial</b>, teniendo en cuenta las observaciones anteriores.
    </span></div>

In [2]:
def gauss_pp(A, B):
    m, n = shape(A)
    p, q = shape(B)
    if m != n or n != p or q < 1:
        return False, "Error gauss_pp: error en las dimensiones."
    if A.dtype == complex or B.dtype == complex:
        gaussA = array(A, dtype=complex)
        gaussB = array(B, dtype=complex)
    else:
        gaussA = array(A, dtype=float)
        gaussB = array(B, dtype=float)
    for k in range(n-1):
        pos = argmax(abs(gaussA[k:, k])) # Elección del pívot (argmax da la posicion!! del maximo valor de los elementos)
        ik = pos+k # Posicion absoluta (no relativa al tamaño k-ésimo!!)
        if ik != k: # Si pivot no está en posición natural, permutamos las filas
            gaussA[[ik, k], :] = gaussA[[k, ik], :]
            gaussB[[ik, k], :] = gaussB[[k, ik], :]
        if abs(gaussA[k, k]) >= 1e-200:
            for i in range(k+1, n):
                gaussA[i, k] = gaussA[i, k]/gaussA[k, k] 
                gaussA[i, k+1:] -= gaussA[i, k]*gaussA[k, k+1:]
                gaussB[i, :] -= gaussA[i, k]*gaussB[k, :]
    exito, X = remonte(gaussA, gaussB)
    return exito, X

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 2.</b></span> Elaborar un programa de nombre <span style="font-family: Courier">gaussjordan_pp()</span> que implemente el algoritmo del <b>método de Gauss-Jordan</b>, con estrategia de <b>pivote parcial</b>, teniendo en cuenta las observaciones anteriores.
    </span></div>

In [30]:
def gaussjordan_pp(A, B): #método de Gauss-Jordan pivote parcial
    m, n = shape(A)
    p, q = shape(B)
    if m != n or n != p or q < 1:
        return False, "Error gaussjordan_pp: error en las dimensiones."
    if A.dtype == complex or B.dtype == complex:
        gJA = array(A, dtype=complex) # a_1, a_2, a_3 ...
        gJB = array(B, dtype=complex) # b_1, b_2, b_3 ...
    else:
        gJA = array(A, dtype=float)
        gJB = array(B, dtype=float)
        
    for k in range(n):
        pos = argmax(abs(gJA[k:, k])) #argmax da la posicion del maximo valor seleccionado
        ik = pos+k
        if ik != k:
            gJA[[ik, k], :] = gJA[[k, ik], :]
            gJB[[ik, k], :] = gJB[[k, ik], :]
        if abs(gJA[k, k]) >= 1e-200:
            
            for i in range(k): #por encima de la diagonal
                gJA[i, k] = gJA[i, k]/gJA[k, k]
                gJA[i, k+1:] -= gJA[i, k]*gJA[k, k+1:]
                gJB[i, :] -= gJA[i, k]*gJB[k, :]
                
            for i in range(k+1, n): #por debajo de la diagonal
                gJA[i, k] = gJA[i, k]/gJA[k, k]
                gJA[i, k+1:] -= gJA[i, k]*gJA[k, k+1:]
                gJB[i, :] -= gJA[i, k]*gJB[k, :]
                
    if min(abs(diag(gJA))) < 1e-200:
        return False, "Error gaussjordan_pp: matriz singular"
    if A.dtype == complex or B.dtype == complex:
        X = zeros((n, q), dtype == complex)
    else:
        X = zeros((n, q), dtype = float)
    for i in range (n):
        X[i, :] = gJB[i, :]/gJA[i, i]

    return True, X

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3.</b></span> Resolver los siguientes sistemas de ecuaciones lineales mediante los métodos de Gauss y de Gauss-Jordan, con estrategias de pivote parcial:
\[
\mbox{(a)} \quad \left( \begin{array}{rrrr}
1 & 2 & 1 & 4 \\ 2 & 0 & 4 & 3 \\ 4 & 2 & 2 & 1 \\ -3 & 1 & 3 & 2
\end{array} \right) \, \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{array} \right) = \left( \begin{array}{r}
13 \\ 28 \\ 20 \\ 6
\end{array} \right) \qquad \mbox{(b)} \quad \left( \begin{array}{rrrr}
20514 & 4424 & 978 & 224 \\ 4424 & 978 & 224 & 54 \\ 978 & 224 & 54 & 14 \\ 224 & 54 & 14 & 4
\end{array} \right) \, \left( \begin{array}{c}
x_1 \\ x_2 \\ x_3 \\ x_4
\end{array} \right) =  \left( \begin{array}{r}
20514 \\ 4424 \\ 978 \\ 224
\end{array} \right)
\]
    </span></div>

In [31]:
# Ejercicio 3-a.
print("Ejercicio 3-a.")
A = array([[1, 2, 1, 4], [2, 0, 4, 3], [4, 2, 2, 1], [-3, 1, 3, 2]])
print("Matriz: A = \n", A)
B = array([[13], [28], [20], [6]])
print("Segundo miembro: B = \n", B)

exito, X = gauss_pp(A, B)
if exito:
    print("Solución Gauss: X = \n", X)
    print("\nComprobación: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print("Error ", X)
    
exito, X = gaussjordan_pp(A, B)
if exito:
    print("\nSolución Gauss Jordan: X = \n", X)
    print("\nComprobación: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print("Error ", X)

Ejercicio 3-a.
Matriz: A = 
 [[ 1  2  1  4]
 [ 2  0  4  3]
 [ 4  2  2  1]
 [-3  1  3  2]]
Segundo miembro: B = 
 [[13]
 [28]
 [20]
 [ 6]]
Solución Gauss: X = 
 [[ 3.]
 [-1.]
 [ 4.]
 [ 2.]]

Comprobación: ||B-A@X||_2 =  0.0

Solución Gauss Jordan: X = 
 [[ 3.]
 [-1.]
 [ 4.]
 [ 2.]]

Comprobación: ||B-A@X||_2 =  0.0


In [37]:
# Ejercicio 3-b.
print("Ejercicio 3-b.")
A = array([[20514, 4424, 978, 224], [4424, 978, 224, 54], [978, 224, 54, 14], [224, 54, 14, 4]])
print("Matriz: A = \n", A)
B = array([[20514], [4424], [978], [224]])
print("Segundo miembro: B = \n", B)  

exito, X = gauss_pp(A, B)
if exito:
    print("Solución Gauss: X = \n", X)
    print("\nComprobación: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print("Error ", X)
    
exito, X = gaussjordan_pp(A, B)
if exito:
    print("\nSolución Gauss Jordan: X = \n", X)
    print("\nComprobación: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print("Error ", X)

Ejercicio 3-b.
Matriz: A = 
 [[20514  4424   978   224]
 [ 4424   978   224    54]
 [  978   224    54    14]
 [  224    54    14     4]]
Segundo miembro: B = 
 [[20514]
 [ 4424]
 [  978]
 [  224]]
Solución Gauss: X = 
 [[1.]
 [0.]
 [0.]
 [0.]]

Comprobación: ||B-A@X||_2 =  0.0

Solución Gauss Jordan: X = 
 [[1.]
 [0.]
 [0.]
 [0.]]

Comprobación: ||B-A@X||_2 =  0.0


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4.</b></span> Calcular las inversas de las matrices de los sistemas anteriores.
    </span></div>

In [43]:
# Ejercicio 4-a.
# Para calcular las inversas pongo como B = I!!
print("Ejercicio 4-a.")
A = array([[1, 2, 1, 4], [2, 0, 4, 3], [4, 2, 2, 1], [-3, 1, 3, 2]])
print("Matriz: A = \n", A)
B = eye(4)
print("Segundo miembro: B = \n", B)

exito, X = gauss_pp(A, B)
if exito:
    print("\nSolución: X =\n", X) #inversa de A
    print("Comprobación: \n ", norma_mat(B-A@X, 2)) #usamos norma matricial por si la matriz es muy grande
else:
    print(X)
    
exito, X = gaussjordan_pp(A, B)
if exito:
    print("\nSolución: X =\n", X) #inversa de A
    print("Comprobación: \n ", norma_mat(B-A@X, 2)) #usamos norma matricial por si la matriz es muy grande
else:
    print(X)

Ejercicio 4-a.
Matriz: A = 
 [[ 1  2  1  4]
 [ 2  0  4  3]
 [ 4  2  2  1]
 [-3  1  3  2]]
Segundo miembro: B = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Solución: X =
 [[-1.38777878e-17  8.33333333e-02  8.33333333e-02 -1.66666667e-01]
 [ 6.66666667e-02 -3.44444444e-01  3.22222222e-01  2.22222222e-01]
 [-2.00000000e-01  1.16666667e-01  1.16666667e-01  1.66666667e-01]
 [ 2.66666667e-01  1.22222222e-01 -2.11111111e-01 -1.11111111e-01]]
Comprobación: 
  2.857648403497645e-16

Solución: X =
 [[ 0.          0.08333333  0.08333333 -0.16666667]
 [ 0.06666667 -0.34444444  0.32222222  0.22222222]
 [-0.2         0.11666667  0.11666667  0.16666667]
 [ 0.26666667  0.12222222 -0.21111111 -0.11111111]]
Comprobación: 
  1.999937482702541e-16


In [45]:
# Ejercicio 4-b.
print("Ejercicio 4-b.")
A = array([[20514, 4424, 978, 224], [4424, 978, 224, 54], [978, 224, 54, 14], [224, 54, 14, 4]])
print("Matriz: A = \n", A)
B = eye(4)
print("Segundo miembro: B = \n", B)

exito, X = gauss_pp(A, B)
if exito:
    print("\nSolución: X =\n", X) #inversa de A
    print("Comprobación: \n ", norma_mat(B-A@X, 2)) #usamos norma matricial por si la matriz es muy grande
else:
    print(X)
    
exito, X = gaussjordan_pp(A, B)
if exito:
    print("\nSolución: X =\n", X) #inversa de A
    print("Comprobación: \n ", norma_mat(B-A@X, 2)) #usamos norma matricial por si la matriz es muy grande
else:
    print(X)

Ejercicio 4-b.
Matriz: A = 
 [[20514  4424   978   224]
 [ 4424   978   224    54]
 [  978   224    54    14]
 [  224    54    14     4]]
Segundo miembro: B = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Solución: X =
 [[ 5.55555556e-01 -5.83333333e+00  1.92777778e+01 -1.98333333e+01]
 [-5.83333333e+00  6.15000000e+01 -2.04166667e+02  2.11000000e+02]
 [ 1.92777778e+01 -2.04166667e+02  6.81388889e+02 -7.08166667e+02]
 [-1.98333333e+01  2.11000000e+02 -7.08166667e+02  7.41000000e+02]]
Comprobación: 
  7.55524805126398e-11

Solución: X =
 [[ 5.55555556e-01 -5.83333333e+00  1.92777778e+01 -1.98333333e+01]
 [-5.83333333e+00  6.15000000e+01 -2.04166667e+02  2.11000000e+02]
 [ 1.92777778e+01 -2.04166667e+02  6.81388889e+02 -7.08166667e+02]
 [-1.98333333e+01  2.11000000e+02 -7.08166667e+02  7.41000000e+02]]
Comprobación: 
  1.7046095601582439e-10


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 5.</b></span> Para el caso (a) del Ejercicio 3, escribir el sistema final triangular superior resultante $(M\,A)\,X = M\,B$ cuando se utiliza el método de Gauss. Identificar también las matrices $A_k$ y segundos miembros $B_k$, $k=1,2,\ldots,n$ del proceso iterativo.
    </span></div>

In [76]:
def gauss_pp_verbose(A, B):
    m, n = shape(A)
    p, q = shape(B)
    if m != n or n != p or q < 1:
        return False, "Error gauss_pp: error en las dimensiones."
    if A.dtype == complex or B.dtype == complex:
        gaussA = array(A, dtype=complex)
        gaussB = array(B, dtype=complex)
    else:
        gaussA = array(A, dtype=float)
        gaussB = array(B, dtype=float)
    for k in range(n-1):
        print("\nIteración: k = ", k+1)
        pos = argmax(abs(gaussA[k:, k])) # Elección del pívot (argmax da la posicion!! del maximo valor de los elementos)
        ik = pos+k # Posicion absoluta (no relativa al tamaño k-ésimo!!)
        print("Posición pívot: ik = ", ik+1)
        if ik != k: # Si pivot no está en posición natural, permutamos las filas
            gaussA[[ik, k], :] = gaussA[[k, ik], :]
            gaussB[[ik, k], :] = gaussB[[k, ik], :]
        if abs(gaussA[k, k]) >= 1e-200:
            for i in range(k+1, n):
                gaussA[i, k] = gaussA[i, k]/gaussA[k, k] 
                gaussA[i, k+1:] -= gaussA[i, k]*gaussA[k, k+1:]
                gaussB[i, :] -= gaussA[i, k]*gaussB[k, :]
        print("Matriz A_k+1: \n", gaussA)       
    print("\nMatriz triangular (MA): \n", triu(gaussA))
    print("Segundo miembro: \n", gaussB)
    exito, X = remonte(gaussA, gaussB)
    return exito, X

In [78]:
# Ejercicio 5-a.
print("Ejercicio 5-a.")
A = array([[1, 2, 1, 4], [2, 0, 4, 3], [4, 2, 2, 1], [-3, 1, 3, 2]])
print("Matriz: A = ", A)
B = array([[13], [28], [20], [6]])
print("Segundo miembro: B = ", B)
exito, X = gauss_pp_verbose(A, B)
if exito:
    print("\nSolución Gauss: X = \n", X)
    print("\nComprobación: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print("Error ", X)

Ejercicio 5-a.
Matriz: A =  [[ 1  2  1  4]
 [ 2  0  4  3]
 [ 4  2  2  1]
 [-3  1  3  2]]
Segundo miembro: B =  [[13]
 [28]
 [20]
 [ 6]]

Iteración: k =  1
Posición pívot: ik =  3
Matriz A_k+1: 
 [[ 4.    2.    2.    1.  ]
 [ 0.5  -1.    3.    2.5 ]
 [ 0.25  1.5   0.5   3.75]
 [-0.75  2.5   4.5   2.75]]

Iteración: k =  2
Posición pívot: ik =  4
Matriz A_k+1: 
 [[ 4.    2.    2.    1.  ]
 [-0.75  2.5   4.5   2.75]
 [ 0.25  0.6  -2.2   2.1 ]
 [ 0.5  -0.4   4.8   3.6 ]]

Iteración: k =  3
Posición pívot: ik =  4
Matriz A_k+1: 
 [[ 4.          2.          2.          1.        ]
 [-0.75        2.5         4.5         2.75      ]
 [ 0.5        -0.4         4.8         3.6       ]
 [ 0.25        0.6        -0.45833333  3.75      ]]

Matriz triangular (MA): 
 [[4.   2.   2.   1.  ]
 [0.   2.5  4.5  2.75]
 [0.   0.   4.8  3.6 ]
 [0.   0.   0.   3.75]]
Segundo miembro: 
 [[20. ]
 [21. ]
 [26.4]
 [ 7.5]]

Solución Gauss: X = 
 [[ 3.]
 [-1.]
 [ 4.]
 [ 2.]]

Comprobación: ||B-A@X||_2 =  0.0


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 6.</b></span> Para el caso (a) del Ejercicio 3, escribir el sistema final diagonal resultante $(M\,A)\,X = M\,B$ cuando se utiliza el método de Gauss-Jordan. Identificar también las matrices $A_k$ y segundos miembros $B_k$, $k=1,2,\ldots,n+1$ del proceso iterativo.
    </span></div>

In [84]:
def gaussjordan_pp_verbose(A, B): #método de Gauss-Jordan pivote parcial
    m, n = shape(A)
    p, q = shape(B)
    if m != n or n != p or q < 1:
        return False, "Error gaussjordan_pp: error en las dimensiones."
    if A.dtype == complex or B.dtype == complex:
        gJA = array(A, dtype=complex) # a_1, a_2, a_3 ...
        gJB = array(B, dtype=complex) # b_1, b_2, b_3 ...
    else:
        gJA = array(A, dtype=float)
        gJB = array(B, dtype=float)
        
    for k in range(n):
        print("\nIteración: k = ", k)
        pos = argmax(abs(gJA[k:, k])) #argmax da la posicion del maximo valor seleccionado
        ik = pos+k
        print("Posición pívot: ik = ", ik)
        if ik != k:
            gJA[[ik, k], :] = gJA[[k, ik], :]
            gJB[[ik, k], :] = gJB[[k, ik], :]
        if abs(gJA[k, k]) >= 1e-200:
            
            for i in range(k): #por encima de la diagonal
                gJA[i, k] = gJA[i, k]/gJA[k, k]
                gJA[i, k+1:] -= gJA[i, k]*gJA[k, k+1:]
                gJB[i, :] -= gJA[i, k]*gJB[k, :]
                
            for i in range(k+1, n): #por debajo de la diagonal
                gJA[i, k] = gJA[i, k]/gJA[k, k]
                gJA[i, k+1:] -= gJA[i, k]*gJA[k, k+1:]
                gJB[i, :] -= gJA[i, k]*gJB[k, :]
        print("Matriz A_k+1: \n", gJA)   
    print("\nMatriz triangular (MA): \n", triu(gJA))
    print("Segundo miembro: \n", gJB)
    if min(abs(diag(gJA))) < 1e-200:
        return False, "Error gaussjordan_pp: matriz singular"
    if A.dtype == complex or B.dtype == complex:
        X = zeros((n, q), dtype == complex)
    else:
        X = zeros((n, q), dtype = float)
    for i in range (n):
        X[i, :] = gJB[i, :]/gJA[i, i]

    return True, X

In [86]:
# Ejercicio 6-a.
print("Ejercicio 6-a.")
A = array([[1, 2, 1, 4], [2, 0, 4, 3], [4, 2, 2, 1], [-3, 1, 3, 2]])
print("Matriz: A = \n", A)
B = array([[13], [28], [20], [6]])
print("Segundo miembro: B = \n", B)
exito, X = gaussjordan_pp_verbose(A, B)
if exito:
    print("\nSolución: X = \n", X)
    print("Comprobación: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print("Error ", X)

Ejercicio 6-a.
Matriz: A = 
 [[ 1  2  1  4]
 [ 2  0  4  3]
 [ 4  2  2  1]
 [-3  1  3  2]]
Segundo miembro: B = 
 [[13]
 [28]
 [20]
 [ 6]]

Iteración: k =  0
Posición pívot: ik =  2
Matriz A_k+1: 
 [[ 4.    2.    2.    1.  ]
 [ 0.5  -1.    3.    2.5 ]
 [ 0.25  1.5   0.5   3.75]
 [-0.75  2.5   4.5   2.75]]

Iteración: k =  1
Posición pívot: ik =  3
Matriz A_k+1: 
 [[ 4.    0.8  -1.6  -1.2 ]
 [-0.75  2.5   4.5   2.75]
 [ 0.25  0.6  -2.2   2.1 ]
 [ 0.5  -0.4   4.8   3.6 ]]

Iteración: k =  2
Posición pívot: ik =  3
Matriz A_k+1: 
 [[ 4.          0.8        -0.33333333  0.        ]
 [-0.75        2.5         0.9375     -0.625     ]
 [ 0.5        -0.4         4.8         3.6       ]
 [ 0.25        0.6        -0.45833333  3.75      ]]

Iteración: k =  3
Posición pívot: ik =  3
Matriz A_k+1: 
 [[ 4.          0.8        -0.33333333  0.        ]
 [-0.75        2.5         0.9375     -0.16666667]
 [ 0.5        -0.4         4.8         0.96      ]
 [ 0.25        0.6        -0.45833333  3.75      ]

<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Ejercicio 7.</b></span> Elaborar un programa de nombre <span style="font-family: Courier,monospace">gaus_1p()</span> que implemente el algoritmo del <b>método de Gauss</b>, con estrategia de <b>primer pivote no nulo</b>.
    </span></div>

In [69]:
def gauss_1p(A, B):
    m, n = shape(A)
    p, q = shape(B)
    if m != n or n != p or q < 1:
        return False, "Error gauss_1p: error en las dimensiones."
    if A.dtype == complex or B.dtype == complex:
        gaussA = array(A, dtype=complex) # a_1, a_2, a_3 ...
        gaussB = array(B, dtype=complex) # b_1, b_2, b_3 ...
    else:
        gaussA = array(A, dtype=float)
        gaussB = array(B, dtype=float)
    for k in range(n-1):
        for ik in range(k, n):
            if abs(gaussA[ik, k] >= 1e-200):
                break
        if ik != k:
            gaussA[[ik, k], :] = gaussA[[k, ik], :]
            gaussB[[ik, k], :] = gaussB[[k, ik], :]
        if abs(gaussA[k, k]) >= 1e-200:
            for i in range(k+1, n):
                gaussA[i, k] = gaussA[i, k]/gaussA[k, k]
                gaussA[i, k+1:] -= gaussA[i, k]*gaussA[k, k+1:]
                gaussB[i, :] -= gaussA[i, k]*gaussB[k, :]
    exito, X = remonte(gaussA, gaussB) #llama a remonte y resuelve el sistema
    return exito, X

<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Ejercicio 8.</b></span> Elaborar un programa de nombre <span style="font-family: Courier,monospace">gausjordan_1p()</span> que implemente el algoritmo del <b>método de Gauss-Jordan</b>, con estrategia de <b>primer pivote no nulo</b>.
    </span></div>

In [70]:
def gaussjordan_1p(A, B):
    m, n = shape(A)
    p, q = shape(B)
    if m != n or n != p or q < 1:
        return False, "Error gaussjordan_1p: error en las dimensiones."
    if A.dtype == complex or B.dtype == complex:
        gJA = array(A, dtype=complex) # a_1, a_2, a_3 ...
        gJB = array(B, dtype=complex) # b_1, b_2, b_3 ...
    else:
        gJA = array(A, dtype=float)
        gJB = array(B, dtype=float)
    for k in range(n):
        for ik in range(k, n):
            if abs(gJA[ik, k] >= 1e-200):
                break
        pos = argmax(abs(gJA[k:, k])) #argmax da la posicion del maximo valor seleccionado
        ik = pos+k
        if ik != k:
            gJA[[ik, k], :] = gJA[[k, ik], :]
            gJB[[ik, k], :] = gJB[[k, ik], :]
        if abs(gJA[k, k]) >= 1e-200:
            for i in range(k): #por encima de la diagonal
                gJA[i, k] = gJA[i, k]/gJA[k, k]
                gJA[i, k+1:] -= gJA[i, k]*gJA[k, k+1:]
                gJB[i, :] -= gJA[i, k]*gJB[k, :]
            for i in range(k+1, n): #por debajo de la diagonal
                gJA[i, k] = gJA[i, k]/gJA[k, k]
                gJA[i, k+1:] -= gJA[i, k]*gJA[k, k+1:]
                gJB[i, :] -= gJA[i, k]*gJB[k, :]
    if min(abs(diag(gJA))) < 1e-200:
        return False, "Error gaussjordan_1p: matriz singular"
    if A.dtype == complex or B.dtype == complex:
        X = zeros((n, q), dtype == complex)
    else:
        X = zeros((n, q), dtype = float)
    for i in range (n):
        X[i, :] = gJB[i, :]/gJA[i, i]

    return True, X

<div align="justify"><span style="font-family: Arial,Helvetica,sans-serif; font-size: medium; color:#000000"">
    <span style="color:#FF0000"><b>Ejercicio 9.</b></span> Resolver los sistemas de ecuaciones lineales del ejercicio 3 mediante los métodos de Gauss y de Gauss-Jordan, con estrategias de primer pivote no nulo.
    </span></div>

In [74]:
A = array([[1, 2, 1, 4], [2, 0, 4, 3], [4, 2, 2, 1], [-3, 1, 3, 2]])
print("Matriz: A = \n", A)
B = array([[13], [28], [20], [6]])
print("Segundo miembro: B = \n", B)
exito, X = gauss_1p(A, B)
if exito:
    print("Solución Gauss: X = \n", X)
    print("\nComprobación: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print("Error ", X)

Matriz: A = 
 [[ 1  2  1  4]
 [ 2  0  4  3]
 [ 4  2  2  1]
 [-3  1  3  2]]
Segundo miembro: B = 
 [[13]
 [28]
 [20]
 [ 6]]
Solución Gauss: X = 
 [[ 3.]
 [-1.]
 [ 4.]
 [ 2.]]

Comprobación: ||B-A@X||_2 =  1.0805156823142814e-14


In [75]:
A = array([[1, 2, 1, 4], [2, 0, 4, 3], [4, 2, 2, 1], [-3, 1, 3, 2]])
print("Matriz: A = \n", A)
B = array([[13], [28], [20], [6]])
print("Segundo miembro: B = \n", B)
exito, X = gaussjordan_1p(A, B)
if exito:
    print("Solución Gauss: X = \n", X)
    print("\nComprobación: ||B-A@X||_2 = ", norma_vec(B-A@X, 2))
else:
    print("Error ", X)

Matriz: A = 
 [[ 1  2  1  4]
 [ 2  0  4  3]
 [ 4  2  2  1]
 [-3  1  3  2]]
Segundo miembro: B = 
 [[13]
 [28]
 [20]
 [ 6]]
Solución Gauss: X = 
 [[ 3.]
 [-1.]
 [ 4.]
 [ 2.]]

Comprobación: ||B-A@X||_2 =  0.0
