<div align="center"><span style="font-family: Arial; color:#0000FF"><b>
    <span style="font-size: x-large">Métodos Numéricos II</span>
    <br>
    <span style="font-size: large">Segundo de Grado en Matemáticas - Curso 2022/23</span>
    <br>
    <span style="font-size: medium">Facultad de Ciencias de la Universidad de Málaga</span>
    <br>
    <span style="font-size: small">Dpto. de Análisis Matemático, Estadística e Investigación Operativa, y Matemática Aplicada</span>
    <br>
    <span style="font-size: small">Profs. Manuel J. Castro y Francisco J. Palma (Área Conocimiento de Matemática Aplicada)</span>
    <br>
    <span style="font-size: medium; color:#FF0000">Práctica número 7</span>
    </b></span></div>

In [1]:
from algoritmos import *

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 1.</b></span> Dado el vector $X = \left( \begin{array}{c} 1 \\ 2 \\ 3 \\ 4 \end{array} \right) \in \mathbb{R}^4$, calcular la matriz de Householder $H(X) \in \mathcal{M}_4(\mathbb{R})$.
    </span></div>

In [2]:
# Ejercicio 1.
X = array([[1], [2], [3], [4]], dtype=float)
print("Vector: X = \n", X)
H = eye(4) - (2/(conjugada(X)@X))*(X@conjugada(X))
print("Matriz: H(X) = \n", H)

Vector: X = 
 [[1.]
 [2.]
 [3.]
 [4.]]
Matriz: H(X) = 
 [[ 0.93333333 -0.13333333 -0.2        -0.26666667]
 [-0.13333333  0.73333333 -0.4        -0.53333333]
 [-0.2        -0.4         0.4        -0.8       ]
 [-0.26666667 -0.53333333 -0.8        -0.06666667]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 2.</b></span> Dado el vector $X = \left( \begin{array}{c} 1 \\ 2 \\ 3 \\ 4 \end{array} \right) \in \mathbb{R}^4$, calcular las matrices de Householder $H(Z_i) \in \mathcal{M}_4(\mathbb{R})$, $i=1,2$, tales que el vector $H(Z_i)\,X$ tiene nulas todas sus componentes excepto, quizás, la primera.
    </span></div>

In [3]:
# Ejercicio 2.
X = array([[1], [2], [3], [4]])
print("Vector: X = \n", X)

E1 = reshape((eye(4)[0]),(4,1)) # cambiar la forma de una matriz identidad de 4x4 y obtener una matriz de dimensiones 4x1 (usando la primera fila de la matriz).

resTh19 = norma_vec(X,2)*exp(angle(X[0,0])*1j)*E1

Z1 = X + resTh19
H1 = householder(Z1)
Z2 = X - resTh19
H2 = householder(Z2)

print(" H1 = \n", H1)
print(" H2 = \n", H2)
print(" H1@X = \n", H1@X)
print(" H2@X = \n", H2@X)

Vector: X = 
 [[1]
 [2]
 [3]
 [4]]
 H1 = 
 [[-0.18257419+0.j -0.36514837+0.j -0.54772256+0.j -0.73029674+0.j]
 [-0.36514837+0.j  0.88725161+0.j -0.16912258+0.j -0.22549678+0.j]
 [-0.54772256+0.j -0.16912258+0.j  0.74631613+0.j -0.33824516+0.j]
 [-0.73029674+0.j -0.22549678+0.j -0.33824516+0.j  0.54900645+0.j]]
 H2 = 
 [[ 0.18257419+0.j  0.36514837+0.j  0.54772256+0.j  0.73029674+0.j]
 [ 0.36514837+0.j  0.83688632+0.j -0.24467052+0.j -0.32622736+0.j]
 [ 0.54772256+0.j -0.24467052+0.j  0.63299422+0.j -0.48934104+0.j]
 [ 0.73029674+0.j -0.32622736+0.j -0.48934104+0.j  0.34754528+0.j]]
 H1@X = 
 [[-5.47722558e+00+0.j]
 [ 1.11022302e-16+0.j]
 [ 0.00000000e+00+0.j]
 [ 4.44089210e-16+0.j]]
 H2@X = 
 [[ 5.47722558e+00+0.j]
 [-1.66533454e-16+0.j]
 [-4.44089210e-16+0.j]
 [-3.33066907e-16+0.j]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3.</b></span> Considera el sistema lineal $A\,X=B$, así como el sistema perturbado $A\,\bar{X}=\bar{B}$, donde
\[
A = \left( \begin{array}{rrrr} 10 & 1 & 4 & 0 \\ 1 & 10 & 5 & -1 \\ 4 & 5 & 10 & 7 \\ 0 & -1 & 7 & 9 \end{array} \right)\,, \quad B = \left( \begin{array}{r} 15 \\ 15 \\ 26 \\ 15 \end{array} \right) \quad \mbox{y} \quad \bar{B} = \left( \begin{array}{r} 16 \\ 16 \\ 25 \\ 16 \end{array} \right)\,.
\]
    Calcular $X$ y $\bar{X}$ (mediante el método de Gauss con estrategia de pívot parcial) y verificar la desigualdad
\[
\frac{\|\delta X\|_2}{\|X\|_2} \le \rm{cond}_2(A)\,\frac{\|\delta B\|_2}{\|B\|_2}\,.
\]
    </span></div>

In [4]:
# Ejercicio 3.
A = array([[10,1,4,0], [1,10,5,-1], [4,5,10,7], [0,-1,7,9]])
B = array([[15], [15], [26], [15]])
Bmod = array([[16], [16], [25], [16]])

print("Matriz A = \n", A)
print("Matriz B = \n", B)
print("Matriz C = \n", Bmod)

exito, X = gauss_pp(A,B)
if exito:
    print("\nLa solución de AX = B es X = \n", X)

exito, Xmod = gauss_pp(A,Bmod)
if exito:
    print("\nLa solución de AX = Bmod es Xmod = \n", Xmod)
    
print("\nANÁLISIS DE ERRORES:")
errX = Xmod - X
condA = norma_mat(A,2)*norma_mat(inv(A),2)

print("Norma de X: ||X||_2 = ", norma_vec(X,2))
print("Norma de delta_X: ||delta_X||_2 = ", norma_vec(errX,2))

errB = Bmod - B
print("Norma de B: ||B||_2 = ", norma_vec(B,2))
print("Norma de delta_B: ||delta_B||_2 = ", norma_vec(errB,2))

print("Error relativo solución: ||delta_X||_2/||X||_2 = ", norma_vec(errX,2)/norma_vec(X,2))
print("Condicionamiento: cond_2(A) = ", condA)
print("Error relativo datos: ||delta_B||_2/||B||_2 = ", norma_vec(errB,2)/norma_vec(B,2))

exito = norma_vec(errX,2)/norma_vec(X,2) <= condA * norma_vec(errB,2)/norma_vec(B,2)
print("Verificación del teorema: ", exito)
print("Primer término de la desigualdad: ", norma_vec(errX,2)/norma_vec(X,2))
print("Segundo término de la desigualdad: ", condA * norma_vec(errB,2)/norma_vec(B,2))

Matriz A = 
 [[10  1  4  0]
 [ 1 10  5 -1]
 [ 4  5 10  7]
 [ 0 -1  7  9]]
Matriz B = 
 [[15]
 [15]
 [26]
 [15]]
Matriz C = 
 [[16]
 [16]
 [25]
 [16]]

La solución de AX = B es X = 
 [[1.]
 [1.]
 [1.]
 [1.]]

La solución de AX = Bmod es Xmod = 
 [[  832.]
 [ 1324.]
 [-2407.]
 [ 2021.]]

ANÁLISIS DE ERRORES:
Norma de X: ||X||_2 =  1.9999999999994262
Norma de delta_X: ||delta_X||_2 =  3509.950711900965
Norma de B: ||B||_2 =  36.75595189897821
Norma de delta_B: ||delta_B||_2 =  2.0
Error relativo solución: ||delta_X||_2/||X||_2 =  1754.9753559509859
Condicionamiento: cond_2(A) =  35792.39762882573
Error relativo datos: ||delta_B||_2/||B||_2 =  0.05441295617909432
Verificación del teorema:  True
Primer término de la desigualdad:  1754.9753559509859
Segundo término de la desigualdad:  1947.570163722014


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4.</b></span> Calcular $\rm{cond}_p(A_2)$, $p=1,2,\infty$, donde $A_2$ es la matriz triangular superior resultante de aplicar el método de Gauss al sistema
\[
\left\{ \begin{array}{rcrcr} 10^{-4}\,x_1 & + & x_2 & = & 1\,, \\ x_1 & + & x_2 & = & 2\,. \end{array} \right.
\]
    Comparar los resultados cuando no se utiliza ninguna estrategia de pivot y cuando se utiliza una estrategia de pivot parcial.
    <br>
    Cambiar el elemento $(1,1)$ de la matriz de coeficientes por $10^{-16}$ y analizar el resultado.
    </span></div>

In [5]:
def gauss_pp_DevTriangSup(A, B):
    m, n = shape(A)
    p, q = shape(B)
    if m != n or n != p or q < 1:
        return False, "Error gauss_pp_DevTriangSup: error en las dimensiones."
    if A.dtype == complex or B.dtype == complex:
        gaussA = array(A, dtype=complex)
        gaussB = array(B, dtype=complex)
    else:
        gaussA = array(A, dtype=float)
        gaussB = array(B, dtype=float)
    for k in range(n-1):
        pos = argmax(abs(gaussA[k:, k])) # Elección del pívot (argmax da la posicion!! del maximo valor de los elementos)
        ik = pos+k # Posicion absoluta (no relativa al tamaño k-ésimo!!)
        if ik != k: # Si pivot no está en posición natural, permutamos las filas
            gaussA[[ik, k], :] = gaussA[[k, ik], :]
            gaussB[[ik, k], :] = gaussB[[k, ik], :]
        if abs(gaussA[k, k]) >= 1e-200:
            for i in range(k+1, n):
                gaussA[i, k] = gaussA[i, k]/gaussA[k, k] 
                gaussA[i, k+1:] -= gaussA[i, k]*gaussA[k, k+1:]
                gaussB[i, :] -= gaussA[i, k]*gaussB[k, :]
    exito, X = remonte(gaussA, gaussB)
    return exito, X, triu(gaussA)

In [6]:
def metodo_lu_DevTriangSup(A, B):
    m, n = shape(A)
    p, q = shape(B)
    if m!= n or n != p or q < 1:
        return False, "Error metodo_lu: Tamaños erróneos"
    exito,lu = facto_lu(A)
    if exito:
        ex,Y = descenso1(lu,B)
        exito1,X = remonte(lu,Y)
        if exito1:
            return True,X, triu(lu)
        else:
            return False, "Error metodo_lu: factorización LU no inversible"
    else:
        return False, "Error metodo_lu: error en la resolucion"

In [7]:
# Ejercicio 4.
A = array([[1e-4,1],[1,1]])
B = array([[1],[2]])
print("Matriz A=\n",A)
print("Array B=\n",B)

#NINGUNA ESTRATEGIA DE PIVOT = LU

(exito,X,triangSup) = gauss_pp_DevTriangSup(A,B)

print("\nLa matriz triangular superior del método de Gauss es \n", triangSup)
print("\nLa solución del sistema por método de Gauss con pivote es X=\n",X)

print("\ncond1=",condicionamiento(triangSup,1))
print("cond2=",condicionamiento(triangSup,2))
print("cond(inf)=",condicionamiento(triangSup,inf))

(exito,X,triangSup) = metodo_lu_DevTriangSup(A,B)
print(X)

print("\nLa matriz triangular superior del método LU (Gauss sin pivote) es \n", triangSup)
print("\nLa solución del sistema por método LU (Gauss sin pivote) es X=\n",X)

print("\ncond1=",condicionamiento(triangSup,1))
print("cond2=",condicionamiento(triangSup,2))
print("cond(inf)=",condicionamiento(triangSup,inf))


#Cuando cambiamos el a11 por 1e-16 en vez de 1e-4, ocurre que el método LU no da la solución correcta
# y el condicionamiento se dispara (este es el problema de que no se resuelva bien el sistema)


Matriz A=
 [[1.e-04 1.e+00]
 [1.e+00 1.e+00]]
Array B=
 [[1]
 [2]]

La matriz triangular superior del método de Gauss es 
 [[1.     1.    ]
 [0.     0.9999]]

La solución del sistema por método de Gauss con pivote es X=
 [[1.00010001]
 [0.99989999]]

cond1= 4.000200020002
cond2= 2.618151093313238
cond(inf)= 4.000200020002
[[1.00010001]
 [0.99989999]]

La matriz triangular superior del método LU (Gauss sin pivote) es 
 [[ 1.000e-04  1.000e+00]
 [ 0.000e+00 -9.999e+03]]

La solución del sistema por método LU (Gauss sin pivote) es X=
 [[1.00010001]
 [0.99989999]]

cond1= 100000000.0
cond2= 99990001.0001
cond(inf)= 99999999.99999999


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 5.</b></span> Analizar si la matriz
\[
A = \left( \begin{array}{cccc} 1 & 2 & 1 & 1 \\ 2 & 3 & 4 & 3 \\ 1 & 4 & -4 & 0 \\ 1 & 3 & 0 & 0 \end{array} \right)
\]
    es definida positiva.
    </span></div>

In [8]:
# Ejercicio 5.
# Corolario 15. Dada A simétrica, existe la factorización Cholesky si y solo si A es definida positiva

A = array([[1,2,1,1], [2,3,4,3], [1,4,-4,0], [1,3,0,0]])
print("Matriz A = \n", A)
exito, chol = facto_cholesky(A)
if exito:
    print("\nEs definida positiva")
else:
    print("\nNo es definida positiva")

Matriz A = 
 [[ 1  2  1  1]
 [ 2  3  4  3]
 [ 1  4 -4  0]
 [ 1  3  0  0]]

No es definida positiva
