<div align="center"><span style="font-family: Arial; color:#0000FF"><b>
    <span style="font-size: x-large">Métodos Numéricos II</span>
    <br>
    <span style="font-size: large">Segundo de Grado en Matemáticas - Curso 2022/23</span>
    <br>
    <span style="font-size: medium">Facultad de Ciencias de la Universidad de Málaga</span>
    <br>
    <span style="font-size: small">Dpto. de Análisis Matemático, Estadística e Investigación Operativa, y Matemática Aplicada</span>
    <br>
    <span style="font-size: small">Profs. Manuel J. Castro y Francisco J. Palma (Área Conocimiento de Matemática Aplicada)</span>
    <br>
    <span style="font-size: medium; color:#FF0000">Práctica número 2</span>
    </b></span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    En primer lugar cargamos los módulos necesarios.
    </span></div>

In [2]:
# -*- coding: utf-8 -*-
from numpy import *
from numpy.linalg import *
from numpy import abs, sum, max, min

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    El primer objetivo de esta práctica es ver la forma en la que podemos <b>definir nuestras propias funciones</b> que implementen un determinado algoritmo.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Por ejemplo, nos podemos plantear definir una función, a la que llamaremos <span style="font-family: Courier">conjugada()</span>, que calcule la <b>conjugada</b> de una matriz.
    <br>
    Esta función debe tener un único argumento de entrada, que es una matriz $A\in\mathcal{M}_{m\times n}(\mathbb{C})$, y debe devolver su matriz conjugada $A^*\in\mathcal{M}_{n\times m}(\mathbb{C})$. El código necesario para llevar a cabo esta tarea puede ser tan simple como este que sigue.
    </span></div>

In [3]:
def conjugada(A): #Matriz Adjunta
    nd = ndim(A)
    if nd == 1:
        AA = array([A]) #Meto una matriz fila en una matriz
    elif nd == 2:
        AA = array(A) #Concluyo igual (Copia Literal)
    else:
        AA = 0
        print("Error con conjugada")
    return conjugate(transpose(AA))
    

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 1.</b></span> Calcular las conjugadas de las matrices: (a) $A = \left( \begin{array}{cc} 1 & 4\,i \\ 2 & -5\,i \\ 3 & 6+6\,i \end{array} \right)$; (b) $B = \left( \begin{array}{cc} 1 & 4\,i \end{array} \right)$; (c) $C = \left( \begin{array}{c} 1 \\ 2 \\ 3 \end{array} \right)$.
    </span></div>

In [4]:
# Ejercicio 1-a.
print("Ejercicio 1-a.")
A = array([[1, 4j], [2, -5j], [3, 6+6j]])
print("Matriz: A = \n", A)
print("Conjugada: A^* = \n", conjugada(A))

Ejercicio 1-a.
Matriz: A = 
 [[ 1.+0.j  0.+4.j]
 [ 2.+0.j -0.-5.j]
 [ 3.+0.j  6.+6.j]]
Conjugada: A^* = 
 [[ 1.-0.j  2.-0.j  3.-0.j]
 [ 0.-4.j -0.+5.j  6.-6.j]]


In [5]:
# Ejercicio 1-b.
print("Ejercicio 1-b.")
B = array([[1, 4j]]) # Matriz con única fila
print("B = \n", B)
print("B^* = \n", conjugada(B))

Ejercicio 1-b.
B = 
 [[1.+0.j 0.+4.j]]
B^* = 
 [[1.-0.j]
 [0.-4.j]]


In [6]:
# Ejercicio 1-c.
print("Ejercicio 1-c.")
C = array([[1], [2], [3]]) #Matriz con única columna
print("C = \n", C)
print("C^* = \n", conjugada(C))

Ejercicio 1-c.
C = 
 [[1]
 [2]
 [3]]
C^* = 
 [[1 2 3]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 2.</b></span> Mejorar la función anterior en el siguiente sentido: como se puede comprobar, si el argumento de entrada es un vector (array de una dimensión), la función devuelve también un vector con los elementos conjugados; modificar la función creada para que en este caso considere el vector como una matriz fila y devuelva, por tanto, una matriz columna (evidentemente con los elementos conjugados).
    <br>
    Comprobar la validez de la mejora realizada utilizando el vector $x=(1+i\,,\,2-2\,i\,,\,-3+3\,i)$.
    </span></div>

In [7]:
# Ejercicio 2.
print("Ejercicio 2.")
x = array([1+1j, 2-2j, -3+3j])
print("x = \n", x)
print("x^* = \n", conjugada(x))

Ejercicio 2.
x = 
 [ 1.+1.j  2.-2.j -3.+3.j]
x^* = 
 [[ 1.-1.j]
 [ 2.+2.j]
 [-3.-3.j]]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    El siguiente objetivo de esta práctica es calcular los <b>autovalores</b> y <b>autovectores</b> de una matriz, <b>diagonalizarla</b> (si es posible) y calcular sus <b>valores singulares</b>.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
   Dada una matriz $A\in\mathcal{M}_n(\mathbb{K})$, sus <b>autovalores</b> y <b>autovectores</b> pueden calcularse con la ayuda de la función <span style="font-family: Courier">eig()</span>; esta función tiene un único argumento de entrada que es la matriz cuadrada $A$ y tiene dos argumentos de salida, siendo el primero un vector de $n$ componentes conteniendo a los autovalores (en un orden arbitrario, quizás números complejos aunque la matriz sea de coeficientes reales y repetidos en caso de multiplicidad mayor que uno) y el segundo una matriz cuadrada de orden $n$ cuyas columnas son autovectores (asociados a los autovalores calculados, en el mismo orden y unitarios respecto del producto escalar ordinario).
    <br>
    No obstante la matriz de autovectores puede no ser regular en el caso de que la matriz dada no sea diagonalizable (los autovectores asociados a autovalores con multiplicidad mayor que 1 no son linealmente independientes).
    <br>
    En el caso de que la matriz dada sí sea diagonalizable, la matriz de autovectores que obtenemos es regular, pero aunque tengamos asegurado que existe una matriz de paso ortogonal-unitaria (al ser la matriz dada normal), la que obtenemos no lo es necesariamente.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3 (a).</b></span> Calcular los autovalores y autovectores, y ver si es diagonalizable la matriz $A = \left( \begin{array}{rr} 3 & 1 \\ 0 & 1 \end{array} \right)$.
    <br>
    Imprimir el vector de autovalores y la matriz de autovectores (ortogonal-unitaria si es posible) y comprobar si la matriz dada es diagonalizable (comprobar que $P^{-1}\,A\,P=D$ para lo cual se puede utilizar la función <span style="font-family: Courier">inv()</span> que calcula la inversa de la función dada como argumento). 
    </span></div>

In [8]:
# Ejercicio 3-a.
print("Ejercicio 3-a.")
A = array([[3, 1], [0, 1]])
print("Matriz: A = \n", A)
d, P = eig(A) # eig devuelve dos valores, vectores de autovalores y matriz de autovalores cuyas columnas son autovalores
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("\ndet(P) = ", detP)
if abs(detP) > 1.e-10: # No mirar si es igual a cero, si no mirar mayor que un error
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P # Matriz D
    print("\ninv(P)@A@P = \n", D)
    print("\nComprobación: ", max(abs(D - diag(d)))) #Compruebo si D es una matriz diagonalizable, valor cercano a 0 si es verdad.
else:
    print("La matriz no es diagonalizable.")

Ejercicio 3-a.
Matriz: A = 
 [[3 1]
 [0 1]]
Vector de autovalores: d =  [3. 1.]
Matriz de autovectores: P = 
 [[ 1.         -0.4472136 ]
 [ 0.          0.89442719]]

det(P) =  0.8944271909999159
La matriz es diagonalizable.

inv(P)@A@P = 
 [[3. 0.]
 [0. 1.]]

Comprobación:  0.0


In [91]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = \n", normal)
mv = max(abs(normal))
if mv > 1.e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.") #Matriz diagonalizable pero no con unitaria normal (Schur)

A@A^* - A^*@A = 
 [[ 1 -2]
 [-2 -1]]
La matriz no es normal.


In [92]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = \n", unit)
mv = max(abs(unit - eye(n)))
if mv > 1.e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P = 
 [[ 1.        -0.4472136]
 [-0.4472136  1.       ]]
La matriz de paso no es ortogonal-unitaria.


In [93]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector: x = ", P[:, i]) #Distintas columnas, no filas, de P

Autovalor: lambda =  3.0  Autovector: x =  [1. 0.]
Autovalor: lambda =  1.0  Autovector: x =  [-0.4472136   0.89442719]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3 (b).</b></span> Ídem con la matriz $A = \left( \begin{array}{rr} 0 & -2 \\ 2 & 0 \end{array} \right)$.
    </span></div>

In [8]:
# Ejercicio 3-b.
print("Ejercicio 3-b.") # Antisimétrica => (Valores Puramente Imaginarios) Regular Normal Unitaria => Diagonalizable
A = array([[0, -2], [2, 0]])
print("Matriz: A = \n", A)
d, P = eig(A) # eig devuelve dos valores, vectores de autovalores y matriz de autovalores
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("\ndet(P) = ", detP)
if abs(detP) > 1.e-10: # No mirar si es igual a cero, si no mirar mayor que un error
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P # Matriz D
    print("\ninv(P)@A@P = \n", D)
    print("\nComprobación: ", max(abs(D - diag(d)))) #Compruebo si D es una matriz diagonalizable, valor cercano a 0 si es verdad.
else:
    print("La matriz no es diagonalizable.")

Ejercicio 3-b.
Matriz: A = 
 [[ 0 -2]
 [ 2  0]]
Vector de autovalores: d =  [0.+2.j 0.-2.j]
Matriz de autovectores: P = 
 [[0.        +0.70710678j 0.        -0.70710678j]
 [0.70710678+0.j         0.70710678-0.j        ]]

det(P) =  1j
La matriz es diagonalizable.

inv(P)@A@P = 
 [[0.+2.0000000e+00j 0.+4.4408921e-16j]
 [0.-4.4408921e-16j 0.-2.0000000e+00j]]

Comprobación:  4.440892098500626e-16


In [9]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = \n", normal)
mv = max(abs(normal))
if mv > 1.e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A = 
 [[0 0]
 [0 0]]
La matriz es normal.


In [10]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = \n", unit)
mv = max(abs(unit - eye(n)))
if mv > 1.e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P = 
 [[1.00000000e+00+0.j 2.22044605e-16+0.j]
 [2.22044605e-16+0.j 1.00000000e+00+0.j]]
La matriz de paso es ortogonal-unitaria.


In [11]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector: x = ", P[:, i]) #Distintas columnas, no filas, de P

Autovalor: lambda =  2.0000000000000004j  Autovector: x =  [0.        +0.70710678j 0.70710678+0.j        ]
Autovalor: lambda =  -2.0000000000000004j  Autovector: x =  [0.        -0.70710678j 0.70710678-0.j        ]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3 (c).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrr} 2 & 0 & 2 \\ 0 & 1 & 0 \\ 2 & 0 & -1 \end{array} \right)$.
    </span></div>

In [12]:
# Ejercicio 3-c.
print("Ejercicio 3-c.")
A = array([[2, 0 ,2], [0, 1, 0], [2, 0, -1]])
print("Matriz: A = \n", A)
d, P = eig(A) # eig devuelve dos valores, vectores de autovalores y matriz de autovalores
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("\ndet(P) = ", detP)
if abs(detP) > 1.e-10: # No mirar si es igual a cero, si no mirar mayor que un error
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P # Matriz D
    print("\ninv(P)@A@P = \n", D)
    print("\nComprobación: ", max(abs(D - diag(d)))) #Compruebo si D es una matriz diagonalizable, valor cercano a 0 si es verdad.
else:
    print("La matriz no es diagonalizable.")

Ejercicio 3-c.
Matriz: A = 
 [[ 2  0  2]
 [ 0  1  0]
 [ 2  0 -1]]
Vector de autovalores: d =  [ 3. -2.  1.]
Matriz de autovectores: P = 
 [[ 0.89442719 -0.4472136   0.        ]
 [ 0.          0.          1.        ]
 [ 0.4472136   0.89442719  0.        ]]

det(P) =  -1.0
La matriz es diagonalizable.

inv(P)@A@P = 
 [[ 3.00000000e+00  2.22044605e-16  0.00000000e+00]
 [ 0.00000000e+00 -2.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]

Comprobación:  2.220446049250313e-16


In [13]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = \n", normal)
mv = max(abs(normal))
if mv > 1.e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A = 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
La matriz es normal.


In [76]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = \n", unit)
mv = max(abs(unit - eye(n)))
if mv > 1.e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
La matriz de paso es ortogonal-unitaria.


In [77]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector: x = ", P[:, i]) #Distintas columnas, no filas, de P

Autovalor: lambda =  3.0  Autovector: x =  [0.89442719 0.         0.4472136 ]
Autovalor: lambda =  -2.0  Autovector: x =  [-0.4472136   0.          0.89442719]
Autovalor: lambda =  1.0  Autovector: x =  [0. 1. 0.]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3 (d).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrr} 1 & 0 & 0 \\ -3 & 1 & 0 \\ 4 & -7 & 1 \end{array} \right)$.
    </span></div>

In [78]:
# Ejercicio 3-d.
print("Ejercicio 3-d.")
A = array([[1, 0 ,0], [-3, 1, 0], [4, -7, 1]])
print("Matriz: A = \n", A)
d, P = eig(A) # eig devuelve dos valores, vectores de autovalores y matriz de autovalores
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("\ndet(P) = ", detP)
if abs(detP) > 1.e-10: # No mirar si es igual a cero, si no mirar mayor que un error
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P # Matriz D
    print("\ninv(P)@A@P = \n", D)
    print("\nComprobación: ", max(abs(D - diag(d)))) #Compruebo si D es una matriz diagonalizable, valor cercano a 0 si es verdad.
else:
    print("La matriz no es diagonalizable.")

Ejercicio 3-d.
Matriz: A = 
 [[ 1  0  0]
 [-3  1  0]
 [ 4 -7  1]]
Vector de autovalores: d =  [1. 1. 1.]
Matriz de autovectores: P = 
 [[0.00000000e+00 0.00000000e+00 2.34780031e-33]
 [0.00000000e+00 3.17206578e-17 3.17206578e-17]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00]]

det(P) =  -7.447377042542653e-50
La matriz no es diagonalizable.


In [79]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = \n", normal)
mv = max(abs(normal))
if mv > 1.e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A = 
 [[-25  28   0]
 [ 28 -40 -12]
 [  0 -12  65]]
La matriz no es normal.


In [80]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = \n", unit)
mv = max(abs(unit - eye(n)))
if mv > 1.e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P = 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
La matriz de paso no es ortogonal-unitaria.


In [81]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector: x = ", P[:, i]) #Distintas columnas, no filas, de P

Autovalor: lambda =  1.0  Autovector: x =  [0. 0. 1.]
Autovalor: lambda =  1.0  Autovector: x =  [0.00000000e+00 3.17206578e-17 1.00000000e+00]
Autovalor: lambda =  1.0  Autovector: x =  [2.34780031e-33 3.17206578e-17 1.00000000e+00]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3 (e).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrrr} 1 & 0 & 0 & 1 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & -2 \\ 1 & 0 & -2 & 5 \end{array} \right)$.
    </span></div>

In [15]:
# Ejercicio 3-e.
print("Ejercicio 3-e.")
A = array([[1, 0 ,0, 1], [0, 1, 0, 0], [0, 0, 1, -2], [1, 0, -2, 5]])
print("Matriz: A = \n", A)
d, P = eig(A) # eig devuelve dos valores, vectores de autovalores y matriz de autovalores
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("\ndet(P) = ", detP)
if abs(detP) > 1.e-10: # No mirar si es igual a cero, si no mirar mayor que un error
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P # Matriz D
    print("\ninv(P)@A@P = \n", D)
    print("\nComprobación: ", max(abs(D - diag(d)))) #Compruebo si D es una matriz diagonalizable, valor cercano a 0 si es verdad.
else:
    print("La matriz no es diagonalizable.")

Ejercicio 3-e.
Matriz: A = 
 [[ 1  0  0  1]
 [ 0  1  0  0]
 [ 0  0  1 -2]
 [ 1  0 -2  5]]
Vector de autovalores: d =  [6.00000000e+00 1.00000000e+00 4.59534891e-17 1.00000000e+00]
Matriz de autovectores: P = 
 [[-1.82574186e-01  8.94427191e-01 -4.08248290e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 3.65148372e-01  4.47213595e-01  8.16496581e-01  0.00000000e+00]
 [-9.12870929e-01  6.94835567e-17  4.08248290e-01  0.00000000e+00]]

det(P) =  -1.0
La matriz es diagonalizable.

inv(P)@A@P = 
 [[ 6.00000000e+00 -4.91599416e-16  8.88178420e-16  0.00000000e+00]
 [-1.74942489e-16  1.00000000e+00  9.06493304e-17  0.00000000e+00]
 [-5.06745162e-17  3.85711222e-33  2.26623326e-17  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

Comprobación:  8.881784197001252e-16


In [16]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = \n", normal)
mv = max(abs(normal))
if mv > 1.e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A = 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
La matriz es normal.


In [84]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = \n", unit)
mv = max(abs(unit - eye(n)))
if mv > 1.e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P = 
 [[ 1.00000000e+00 -7.91836773e-18  1.66533454e-16  0.00000000e+00]
 [-7.91836773e-18  1.00000000e+00  8.38776945e-17  0.00000000e+00]
 [ 1.66533454e-16  8.38776945e-17  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
La matriz de paso es ortogonal-unitaria.


In [85]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector: x = ", P[:, i]) #Distintas columnas, no filas, de P

Autovalor: lambda =  6.0  Autovector: x =  [-0.18257419  0.          0.36514837 -0.91287093]
Autovalor: lambda =  1.0000000000000002  Autovector: x =  [8.94427191e-01 0.00000000e+00 4.47213595e-01 6.94835567e-17]
Autovalor: lambda =  4.595348908876999e-17  Autovector: x =  [-0.40824829  0.          0.81649658  0.40824829]
Autovalor: lambda =  1.0  Autovector: x =  [0. 1. 0. 0.]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 3 (f).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrrr} 7 & 1 & 1 & 1 \\ 1 & 7 & 1 & 1 \\ 1 & 1 & 7 & 1 \\ 1 & 1 & 1 & 7 \end{array} \right)$.
    </span></div>

In [18]:
# Ejercicio 3-f.
print("Ejercicio 3-f.")
A = ones((4, 4)) + 6*eye(4)
print("Matriz: A = \n", A)
d, P = eig(A) # eig devuelve dos valores, vectores de autovalores y matriz de autovalores
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("\ndet(P) = ", detP)
if abs(detP) > 1.e-10: # No mirar si es igual a cero, si no mirar mayor que un error
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P # Matriz D
    print("\ninv(P)@A@P = \n", D)
    print("\nComprobación: ", max(abs(D - diag(d)))) #Compruebo si D es una matriz diagonalizable, valor cercano a 0 si es verdad.
else:
    print("La matriz no es diagonalizable.")

Ejercicio 3-f.
Matriz: A = 
 [[7. 1. 1. 1.]
 [1. 7. 1. 1.]
 [1. 1. 7. 1.]
 [1. 1. 1. 7.]]
Vector de autovalores: d =  [ 6. 10.  6.  6.]
Matriz de autovectores: P = 
 [[-0.8660254   0.5         0.0814746   0.23168376]
 [ 0.28867513  0.5        -0.60194778 -0.78090594]
 [ 0.28867513  0.5         0.75801897 -0.03009043]
 [ 0.28867513  0.5        -0.23754579  0.57931262]]

det(P) =  -0.9100502946314354
La matriz es diagonalizable.

inv(P)@A@P = 
 [[ 6.00000000e+00  1.33226763e-15  2.22044605e-16  2.22044605e-16]
 [ 8.88178420e-16  1.00000000e+01  0.00000000e+00 -1.33226763e-15]
 [ 0.00000000e+00  0.00000000e+00  6.00000000e+00 -4.44089210e-16]
 [ 2.22044605e-16  0.00000000e+00 -2.22044605e-16  6.00000000e+00]]

Comprobación:  3.552713678800501e-15


In [19]:
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = \n", normal)
mv = max(abs(normal))
if mv > 1.e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

A@A^* - A^*@A = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
La matriz es normal.


In [20]:
normal = P@conjugada(P) - conjugada(P)@P
print("A@A^* - A^*@A = \n", normal)
mv = max(abs(normal))
if mv > 1.e-10:
    print("La matriz de paso no es normal.")
else:
    print("La matriz de paso es normal.")

A@A^* - A^*@A = 
 [[ 0.06031547 -0.22996668  0.14886659  0.38238873]
 [-0.22996668  0.30548856 -0.09945671  0.02393483]
 [ 0.14886659 -0.09945671 -0.09116847 -0.1926812 ]
 [ 0.38238873  0.02393483 -0.1926812  -0.27463556]]
La matriz de paso no es normal.


In [88]:
# Matriz de paso ortogonal-unitaria.
n = size(d)
unit = conjugada(P)@P
print("P^*@P = \n", unit)
mv = max(abs(unit - eye(n)))
if mv > 1.e-10:
    print("La matriz de paso no es ortogonal-unitaria.")
else:
    print("La matriz de paso es ortogonal-unitaria.")

P^*@P = 
 [[ 1.00000000e+00 -5.55111512e-17 -9.40787620e-02 -2.67525357e-01]
 [-5.55111512e-17  1.00000000e+00 -2.77555756e-17 -1.66533454e-16]
 [-9.40787620e-02 -2.77555756e-17  1.00000000e+00  3.28518553e-01]
 [-2.67525357e-01 -1.66533454e-16  3.28518553e-01  1.00000000e+00]]
La matriz de paso no es ortogonal-unitaria.


In [89]:
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector: x = ", P[:, i]) #Distintas columnas, no filas, de P

Autovalor: lambda =  6.0  Autovector: x =  [-0.8660254   0.28867513  0.28867513  0.28867513]
Autovalor: lambda =  9.999999999999998  Autovector: x =  [0.5 0.5 0.5 0.5]
Autovalor: lambda =  5.999999999999999  Autovector: x =  [ 0.0814746  -0.60194778  0.75801897 -0.23754579]
Autovalor: lambda =  6.0  Autovector: x =  [ 0.23168376 -0.78090594 -0.03009043  0.57931262]


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    Dada una matriz $A\in\mathcal{M}_n(\mathbb{K})$, sus <b>valores singulares</b> pueden calcularse con la ayuda de la función <span style="font-family: Courier">svd()</span>; esta función tiene un único argumento de entrada que es la matriz cuadrada $A$ y tiene tres argumentos de salida, siendo el segundo un vector de $n$ componentes (reales y mayores o iguales que 0) conteniendo a los valores singulares (en un orden arbitrario y repetidos en caso de multiplicidad mayor que uno) y el primero y tercero las  dos matrices de orden $n$ ortogonales-unitarias de su descomposición en valores singulares.
    <br>
    Si llamamos $S$ a la matriz diagonal cuyos elementos diagonales son los valores singulares de $A$ (en el orden que proporciona la función <span style="font-family: Courier">svd()</span>) y $U$ y $V$ las matrices ortogonales-unitarias que se obtienen como primera y tercera salida de dicha función, se verifica que $U\,S\,V=A$.
    </span></div>

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4 (a).</b></span> Realizar la descomposición en valores singulares de la matriz $A = \left( \begin{array}{rr} 3 & 1 \\ 0 & 1 \end{array} \right)$.
    </span></div>

In [43]:
# Ejercicio 4-a.
print("Ejercicio 4-a.")
A = array([[3, 1], [0, 1]])
print("Matriz: A = \n", A)
U, s, V = svd(A)
print("\nVector de valores singulares: s = ", s)
print("\nMatrices ortogonales-unitarias de la descomposición en valores singulares:")
print("U = \n", U)
print("V = \n", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = \n", DVS)
print("\nComprobación: ", max(abs(DVS - A))) #USV = A por la propiedad, número cercano a 0

Ejercicio 4-a.
Matriz: A = 
 [[3 1]
 [0 1]]

Vector de valores singulares: s =  [3.1795868  0.94351882]

Matrices ortogonales-unitarias de la descomposición en valores singulares:
U = 
 [[ 0.99402894 -0.10911677]
 [ 0.10911677  0.99402894]]
V = 
 [[ 0.93788501  0.34694625]
 [-0.34694625  0.93788501]]
U@diag(s)@V = 
 [[3.00000000e+00 1.00000000e+00]
 [1.61174921e-17 1.00000000e+00]]

Comprobación:  8.881784197001252e-16


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4 (b).</b></span> Ídem con la matriz $A = \left( \begin{array}{rr} 0 & -2 \\ 2 & 0 \end{array} \right)$.
    </span></div>

In [64]:
# Ejercicio 4-b.
print("Ejercicio 4-b.")
A = array([[0, -2], [2, 0]])
print("Matriz: A = \n", A)
U, s, V = svd(A)
print("\nVector de valores singulares: s = ", s)
print("\nMatrices ortogonales-unitarias de la descomposición en valores singulares:")
print("U = \n", U)
print("V = \n", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = \n", DVS)
print("\nComprobación: ", max(abs(DVS - A))) #USV = A por la propiedad, número cercano a 0

Ejercicio 4-b.
Matriz: A = 
 [[ 0 -2]
 [ 2  0]]

Vector de valores singulares: s =  [2. 2.]

Matrices ortogonales-unitarias de la descomposición en valores singulares:
U = 
 [[ 0. -1.]
 [-1.  0.]]
V = 
 [[-1. -0.]
 [ 0.  1.]]
U@diag(s)@V = 
 [[ 0. -2.]
 [ 2.  0.]]

Comprobación:  0.0


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4 (c).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrr} 2 & 0 & 2 \\ 0 & 1 & 0 \\ 2 & 0 & -1 \end{array} \right)$.
    </span></div>

In [65]:
# Ejercicio 4-c.
print("Ejercicio 4-c.")
A = array([[2, 0 ,2], [0, 1, 0], [2, 0, -1]])
print("Matriz: A = \n", A)
U, s, V = svd(A)
print("\nVector de valores singulares: s = ", s)
print("\nMatrices ortogonales-unitarias de la descomposición en valores singulares:")
print("U = \n", U)
print("V = \n", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = \n", DVS)
print("\nComprobación: ", max(abs(DVS - A))) #USV = A por la propiedad, número cercano a 0

Ejercicio 4-c.
Matriz: A = 
 [[ 2  0  2]
 [ 0  1  0]
 [ 2  0 -1]]

Vector de valores singulares: s =  [3. 2. 1.]

Matrices ortogonales-unitarias de la descomposición en valores singulares:
U = 
 [[-0.89442719 -0.4472136   0.        ]
 [ 0.          0.          1.        ]
 [-0.4472136   0.89442719  0.        ]]
V = 
 [[-0.89442719  0.         -0.4472136 ]
 [ 0.4472136   0.         -0.89442719]
 [ 0.          1.          0.        ]]
U@diag(s)@V = 
 [[ 2.  0.  2.]
 [ 0.  1.  0.]
 [ 2.  0. -1.]]

Comprobación:  1.1102230246251565e-15


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4 (d).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrr} 1 & 0 & 0 \\ -3 & 1 & 0 \\ 4 & -7 & 1 \end{array} \right)$.
    </span></div>

In [66]:
# Ejercicio 4-d.
print("Ejercicio 4-d.")
A = array([[1, 0 ,0], [-3, 1, 0], [4, -7, 1]])
print("Matriz: A = \n", A)
U, s, V = svd(A)
print("\nVector de valores singulares: s = ", s)
print("\nMatrices ortogonales-unitarias de la descomposición en valores singulares:")
print("U = \n", U)
print("V = \n", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = \n", DVS)
print("\nComprobación: ", max(abs(DVS - A))) #USV = A por la propiedad, número cercano a 0

Ejercicio 4-d.
Matriz: A = 
 [[ 1  0  0]
 [-3  1  0]
 [ 4 -7  1]]

Vector de valores singulares: s =  [8.49406432 2.20182024 0.05346907]

Matrices ortogonales-unitarias de la descomposición en valores singulares:
U = 
 [[-0.06601923  0.37536832 -0.92452154]
 [ 0.29463434 -0.87789606 -0.3774773 ]
 [-0.95332684 -0.29731656 -0.05263838]]
V = 
 [[-0.56077155  0.8203284  -0.11223447]
 [ 0.82649357  0.54651139 -0.13503217]
 [-0.0494333  -0.16848327 -0.98446419]]
U@diag(s)@V = 
 [[ 1.00000000e+00  1.19453878e-15 -1.60215828e-16]
 [-3.00000000e+00  1.00000000e+00  5.79682668e-18]
 [ 4.00000000e+00 -7.00000000e+00  1.00000000e+00]]

Comprobación:  1.7763568394002505e-15


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4 (e).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrrr} 1 & 0 & 0 & 1 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & -2 \\ 1 & 0 & -2 & 5 \end{array} \right)$.
    </span></div>

In [67]:
# Ejercicio 4-e.
print("Ejercicio 4-e.")
A = array([[1, 0 ,0, 1], [0, 1, 0, 0], [0, 0, 1, -2], [1, 0, -2, 5]])
print("Matriz: A = \n", A)
U, s, V = svd(A)
print("\nVector de valores singulares: s = ", s)
print("\nMatrices ortogonales-unitarias de la descomposición en valores singulares:")
print("U = \n", U)
print("V = \n", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = \n", DVS)
print("\nComprobación: ", max(abs(DVS - A))) #USV = A por la propiedad, número cercano a 0

Ejercicio 4-e.
Matriz: A = 
 [[ 1  0  0  1]
 [ 0  1  0  0]
 [ 0  0  1 -2]
 [ 1  0 -2  5]]

Vector de valores singulares: s =  [6.00000000e+00 1.00000000e+00 1.00000000e+00 5.99841267e-17]

Matrices ortogonales-unitarias de la descomposición en valores singulares:
U = 
 [[-1.82574186e-01  8.94427191e-01 -7.13644775e-17 -4.08248290e-01]
 [ 0.00000000e+00 -2.22044605e-16 -1.00000000e+00 -2.83710209e-16]
 [ 3.65148372e-01  4.47213595e-01  0.00000000e+00  8.16496581e-01]
 [-9.12870929e-01  0.00000000e+00 -7.13644775e-17  4.08248290e-01]]
V = 
 [[-1.82574186e-01  0.00000000e+00  3.65148372e-01 -9.12870929e-01]
 [ 8.94427191e-01 -1.38777878e-16  4.47213595e-01  0.00000000e+00]
 [-1.42728955e-16 -1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 4.08248290e-01 -2.77555756e-17 -8.16496581e-01 -4.08248290e-01]]
U@diag(s)@V = 
 [[ 1.00000000e+00 -5.27622302e-17  5.49771398e-16  1.00000000e+00]
 [-5.58737773e-17  1.00000000e+00 -9.93013661e-17  6.94761395e-33]
 [-2.29215189e-17 -6.20633538e-17  1

<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 4 (f).</b></span> Ídem con la matriz $A = \left( \begin{array}{rrrr} 7 & 1 & 1 & 1 \\ 1 & 7 & 1 & 1 \\ 1 & 1 & 7 & 1 \\ 1 & 1 & 1 & 7 \end{array} \right)$.
    </span></div>

In [68]:
# Ejercicio 4-f.
print("Ejercicio 4-f.")
A = ones((4, 4)) + 6*eye(4)
print("Matriz: A = \n", A)
U, s, V = svd(A)
print("\nVector de valores singulares: s = ", s)
print("\nMatrices ortogonales-unitarias de la descomposición en valores singulares:")
print("U = \n", U)
print("V = \n", V)
DVS = U@diag(s)@V
print("U@diag(s)@V = \n", DVS)
print("\nComprobación: ", max(abs(DVS - A))) #USV = A por la propiedad, número cercano a 0

Ejercicio 4-f.
Matriz: A = 
 [[7. 1. 1. 1.]
 [1. 7. 1. 1.]
 [1. 1. 7. 1.]
 [1. 1. 1. 7.]]

Vector de valores singulares: s =  [10.  6.  6.  6.]

Matrices ortogonales-unitarias de la descomposición en valores singulares:
U = 
 [[-5.00000000e-01  2.39306446e-17 -4.10239622e-17  8.66025404e-01]
 [-5.00000000e-01 -5.77350269e-01  5.77350269e-01 -2.88675135e-01]
 [-5.00000000e-01 -2.11324865e-01 -7.88675135e-01 -2.88675135e-01]
 [-5.00000000e-01  7.88675135e-01  2.11324865e-01 -2.88675135e-01]]
V = 
 [[-0.5        -0.5        -0.5        -0.5       ]
 [ 0.         -0.57735027 -0.21132487  0.78867513]
 [-0.          0.57735027 -0.78867513  0.21132487]
 [ 0.8660254  -0.28867513 -0.28867513 -0.28867513]]
U@diag(s)@V = 
 [[7. 1. 1. 1.]
 [1. 7. 1. 1.]
 [1. 1. 7. 1.]
 [1. 1. 1. 7.]]

Comprobación:  1.7763568394002505e-15


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 5.</b></span> En aquellos casos del Ejercicio 3 en los que hay autovalores con multiplicidad (dimensión algebraica) mayor que 1, comprobar cuando la dimensión geométrica de los mismos es igual o no (y por tanto la matriz es o no diagonalizable).
    <br>
    <i>Indicación:</i> la función <span style="font-family: Courier">matrix_rank()</span>, cuyo parámetro de entrada es una matriz (no necesariamente cuadrada), devuelve el rango de la misma.
    </span></div>

In [114]:
# Ejercicio 3-d.
print("Ejercicio 3-d.")
A = array([[1, 0 ,0], [-3, 1, 0], [4, -7, 1]])
print("Matriz: A = \n", A)
d, P = eig(A) # eig devuelve dos valores, vectores de autovalores y matriz de autovalores
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("\ndet(P) = ", detP)
if abs(detP) > 1.e-10: # No mirar si es igual a cero, si no mirar mayor que un error
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P # Matriz D
    print("\ninv(P)@A@P = \n", D)
    print("\nComprobación: ", max(abs(D - diag(d)))) #Compruebo si D es una matriz diagonalizable, valor cercano a 0 si es verdad.
else:
    print("La matriz no es diagonalizable.")
    
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector: x = ", P[:, i]) #Distintas columnas, no filas, de P

Ejercicio 3-d.
Matriz: A = 
 [[ 1  0  0]
 [-3  1  0]
 [ 4 -7  1]]
Vector de autovalores: d =  [1. 1. 1.]
Matriz de autovectores: P = 
 [[0.00000000e+00 0.00000000e+00 2.34780031e-33]
 [0.00000000e+00 3.17206578e-17 3.17206578e-17]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00]]

det(P) =  -7.447377042542653e-50
La matriz no es diagonalizable.
Autovalor: lambda =  1.0  Autovector: x =  [0. 0. 1.]
Autovalor: lambda =  1.0  Autovector: x =  [0.00000000e+00 3.17206578e-17 1.00000000e+00]
Autovalor: lambda =  1.0  Autovector: x =  [2.34780031e-33 3.17206578e-17 1.00000000e+00]


In [115]:
# Ejercicio 5-a
print("El autovalor 1 tiene multiplicidad (dimensión algebraica) 3.")
dg = matrix_rank(P)
print("Su dimensión geométrica es ", dg)
print("Por tanto la matriz no es diagonalizable.")

El autovalor 1 tiene multiplicidad (dimensión algebraica) 3.
Su dimensión geométrica es  1
Por tanto la matriz no es diagonalizable.


In [116]:
# Ejercicio 3-e.
print("Ejercicio 3-e.")
A = array([[1, 0 ,0, 1], [0, 1, 0, 0], [0, 0, 1, -2], [1, 0, -2, 5]])
print("Matriz: A = \n", A)
d, P = eig(A) # eig devuelve dos valores, vectores de autovalores y matriz de autovalores
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("\ndet(P) = ", detP)
if abs(detP) > 1.e-10: # No mirar si es igual a cero, si no mirar mayor que un error
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P # Matriz D
    print("\ninv(P)@A@P = \n", D)
    print("\nComprobación: ", max(abs(D - diag(d)))) #Compruebo si D es una matriz diagonalizable, valor cercano a 0 si es verdad.
else:
    print("La matriz no es diagonalizable.")
    
# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector: x = ", P[:, i])

Ejercicio 3-e.
Matriz: A = 
 [[ 1  0  0  1]
 [ 0  1  0  0]
 [ 0  0  1 -2]
 [ 1  0 -2  5]]
Vector de autovalores: d =  [6.00000000e+00 1.00000000e+00 4.59534891e-17 1.00000000e+00]
Matriz de autovectores: P = 
 [[-1.82574186e-01  8.94427191e-01 -4.08248290e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 3.65148372e-01  4.47213595e-01  8.16496581e-01  0.00000000e+00]
 [-9.12870929e-01  6.94835567e-17  4.08248290e-01  0.00000000e+00]]

det(P) =  -1.0
La matriz es diagonalizable.

inv(P)@A@P = 
 [[ 6.00000000e+00 -4.91599416e-16  8.88178420e-16  0.00000000e+00]
 [-1.74942489e-16  1.00000000e+00  9.06493304e-17  0.00000000e+00]
 [-5.06745162e-17  3.85711222e-33  2.26623326e-17  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

Comprobación:  8.881784197001252e-16
Autovalor: lambda =  6.0  Autovector: x =  [-0.18257419  0.          0.36514837 -0.91287093]
Autovalor: lambda =  1.0000000000000002  Autovector: x =  [8

In [117]:
# Ejercicio 5-b
print("El autovalor 1 tiene multiplicidad (dimensión algebraica) 2.")
dg = matrix_rank(P)
print("Su dimensión geométrica es ", dg)
print("Por tanto la matriz no es diagonalizable.")

El autovalor 1 tiene multiplicidad (dimensión algebraica) 2.
Su dimensión geométrica es  4
Por tanto la matriz no es diagonalizable.


In [118]:
# Ejercicio 3-f.
print("Ejercicio 3-f.")
A = ones((4, 4)) + 6*eye(4)
print("Matriz: A = \n", A)
d, P = eig(A) # eig devuelve dos valores, vectores de autovalores y matriz de autovalores
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("\ndet(P) = ", detP)
if abs(detP) > 1.e-10: # No mirar si es igual a cero, si no mirar mayor que un error
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P # Matriz D
    print("\ninv(P)@A@P = \n", D)
    print("\nComprobación: ", max(abs(D - diag(d)))) #Compruebo si D es una matriz diagonalizable, valor cercano a 0 si es verdad.
else:
    print("La matriz no es diagonalizable.")

# Autovalores y autovectores.
n = size(d)
for i in range(n):
    print("Autovalor: lambda = ", d[i], " Autovector: x = ", P[:, i]) #Distintas columnas, no filas, de P


Ejercicio 3-f.
Matriz: A = 
 [[7. 1. 1. 1.]
 [1. 7. 1. 1.]
 [1. 1. 7. 1.]
 [1. 1. 1. 7.]]
Vector de autovalores: d =  [ 6. 10.  6.  6.]
Matriz de autovectores: P = 
 [[-0.8660254   0.5         0.0814746   0.23168376]
 [ 0.28867513  0.5        -0.60194778 -0.78090594]
 [ 0.28867513  0.5         0.75801897 -0.03009043]
 [ 0.28867513  0.5        -0.23754579  0.57931262]]

det(P) =  -0.9100502946314354
La matriz es diagonalizable.

inv(P)@A@P = 
 [[ 6.00000000e+00  1.33226763e-15  2.22044605e-16  2.22044605e-16]
 [ 8.88178420e-16  1.00000000e+01  0.00000000e+00 -1.33226763e-15]
 [ 0.00000000e+00  0.00000000e+00  6.00000000e+00 -4.44089210e-16]
 [ 2.22044605e-16  0.00000000e+00 -2.22044605e-16  6.00000000e+00]]

Comprobación:  3.552713678800501e-15
Autovalor: lambda =  6.0  Autovector: x =  [-0.8660254   0.28867513  0.28867513  0.28867513]
Autovalor: lambda =  9.999999999999998  Autovector: x =  [0.5 0.5 0.5 0.5]
Autovalor: lambda =  5.999999999999999  Autovector: x =  [ 0.0814746  -0.60194

In [120]:
# Ejercicio 5-c
print("El autovalor 6 tiene multiplicidad (dimensión algebraica) 3.")
dg = matrix_rank(P)
print("Su dimensión geométrica es ", dg)
print("Por tanto la matriz no es diagonalizable.")

El autovalor 6 tiene multiplicidad (dimensión algebraica) 3.
Su dimensión geométrica es  4
Por tanto la matriz no es diagonalizable.


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 6.</b></span> En aquellos casos del Ejercicio 3 en los que la matriz es normal y por tanto diagonalizable con matriz de paso unitaria, pero la matriz de paso obtenida no lo es, obtener una nueva matriz de paso que sí lo sea.
    <br>
    <i>Indicación:</i> la función <span style="font-family: Courier">qr()</span>, cuyo parámetro de entrada es una matriz (no necesariamente cuadrada), devuelve dos matrices, siendo la primera de ellas la ortonormalización de Gram-Schmidt de los vectores columnas de la matriz dada.
    </span></div>

In [25]:
# Ejercicio 6
print("Ejercicio 6")

# Ejercicio 3-f.
print("Ejercicio 3-f.")
A = ones((4, 4)) + 6*eye(4)
print("Matriz: A = \n", A)
d, P = eig(A) # eig devuelve dos valores, vectores de autovalores y matriz de autovalores
print("Vector de autovalores: d = ", d)
print("Matriz de autovectores: P = \n", P)
detP = det(P)
print("\ndet(P) = ", detP)
if abs(detP) > 1.e-10: # No mirar si es igual a cero, si no mirar mayor que un error
    print("La matriz es diagonalizable.")
    D = inv(P)@A@P # Matriz D
    print("\ninv(P)@A@P = \n", D)
    print("\nComprobación: ", max(abs(D - diag(d)))) #Compruebo si D es una matriz diagonalizable, valor cercano a 0 si es verdad.
else:
    print("La matriz no es diagonalizable.")
    
# Matriz normal.
normal = A@conjugada(A) - conjugada(A)@A
print("A@A^* - A^*@A = \n", normal)
mv = max(abs(normal))
if mv > 1.e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")
    
normal = P@conjugada(P) - conjugada(P)@P
print("\nP@P^* - P^*@P = \n", normal)
mv = max(abs(normal))
if mv > 1.e-10:
    print("La matriz de paso no es normal.")
else:
    print("La matriz de paso es normal.")

Ejercicio 6
Ejercicio 3-f.
Matriz: A = 
 [[7. 1. 1. 1.]
 [1. 7. 1. 1.]
 [1. 1. 7. 1.]
 [1. 1. 1. 7.]]
Vector de autovalores: d =  [ 6. 10.  6.  6.]
Matriz de autovectores: P = 
 [[-0.8660254   0.5         0.0814746   0.23168376]
 [ 0.28867513  0.5        -0.60194778 -0.78090594]
 [ 0.28867513  0.5         0.75801897 -0.03009043]
 [ 0.28867513  0.5        -0.23754579  0.57931262]]

det(P) =  -0.9100502946314354
La matriz es diagonalizable.

inv(P)@A@P = 
 [[ 6.00000000e+00  1.33226763e-15  2.22044605e-16  2.22044605e-16]
 [ 8.88178420e-16  1.00000000e+01  0.00000000e+00 -1.33226763e-15]
 [ 0.00000000e+00  0.00000000e+00  6.00000000e+00 -4.44089210e-16]
 [ 2.22044605e-16  0.00000000e+00 -2.22044605e-16  6.00000000e+00]]

Comprobación:  3.552713678800501e-15
A@A^* - A^*@A = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
La matriz es normal.

P@P^* - P^*@P = 
 [[ 0.06031547 -0.22996668  0.14886659  0.38238873]
 [-0.22996668  0.30548856 -0.09945671  0.02393483]
 [ 0.14886659

In [28]:
ort, mat = qr(P)
print("F = \n",ort)
normal = ort@conjugada(ort) - conjugada(ort)@ort
print("\nF@F^* - F^*@F = \n", normal)
mv = max(abs(normal))
if mv > 1.e-10:
    print("La matriz no es normal.")
else:
    print("La matriz es normal.")

F = 
 [[-8.66025404e-01 -5.00000000e-01  5.17926092e-17 -3.88444569e-17]
 [ 2.88675135e-01 -5.00000000e-01  5.77350269e-01 -5.77350269e-01]
 [ 2.88675135e-01 -5.00000000e-01 -7.88675135e-01 -2.11324865e-01]
 [ 2.88675135e-01 -5.00000000e-01  2.11324865e-01  7.88675135e-01]]

F@F^* - F^*@F = 
 [[ 0.00000000e+00  1.91107213e-16  7.92186673e-17  9.42151451e-17]
 [ 1.91107213e-16  2.22044605e-16  6.34249200e-17 -4.97442837e-17]
 [ 7.92186673e-17  6.34249200e-17  0.00000000e+00 -6.98656238e-17]
 [ 9.42151451e-17 -4.97442837e-17 -6.98656238e-17  0.00000000e+00]]
La matriz es normal.


<div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Ejercicio 7.</b></span> Para la matriz $A = \left( \begin{array}{rrr} 1 & 2 & 3 \\ 4 & 5 & 6\\ 7 & 8 & 9 \end{array} \right)$, comprobar que los valores singulares de $A$ son efectivamente las raíces cuadradas positivas de los autovalores de $A^*\,A$.
    </span></div>

In [113]:
# Ejercicio 7
print("Ejercicio 7")

A = array([[1,2,3],[4,5,6],[7,8,9]])
U, s, V = svd(A)
print("\nVector de valores singulares: s = ", s)

AA = conjugada(A)@A
d, P = eig(AA) # eig devuelve dos valores, vectores de autovalores y matriz de autovalores
print("\nVector de raíces cuadradas de los autovalores: d = ", sqrt(d))

print("\nComprobación = ", abs(s-d))

Ejercicio 7

Vector de valores singulares: s =  [1.68481034e+01 1.06836951e+00 4.41842475e-16]

Vector de raíces cuadradas de los autovalores: d =  [1.68481034e+01 1.06836951e+00 8.53406751e-08]

Comprobación =  [2.67010483e+02 7.30439051e-02 6.84118835e-15]


 <div align="left"><span style="font-family: Arial; color:#000000; font-size: medium">
    <span style="color:#FF0000"><b>Importante.</b></span> Durante el desarrollo de las clases prácticas vamos a crear un fichero <span style="font-family: Courier">Python</span>, al que daremos el nombre de <span style="font-family: Courier">algoritmos.py</span>, donde almacenaremos todas aquellas funciones propias que definamos durante el curso; esta será la <b>biblioteca</b> de nuestras funciones. A partir de ese momento, podremos utilizar dichas funciones en cualquier hoja de trabajo que estemos utilizando, sin más que importar dicho fichero al principio de la hoja de trabajo con una instrucción del tipo <span style="font-family: Courier">from algoritmos import *</span>.
    <br>
    Cada vez que se modifique dicho fichero, no debemos olvidar guardar su contenido y reinicializar el núcleo de la hoja de trabajo para tener en cuenta dichas modificaciones.
    </span></div>